apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: keycloak-db
  labels:
    app: keycloak-db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: keycloak-db
  template:
    metadata:
      labels:
        app: keycloak-db
    spec:
      containers:
        - name: keycloak-db
          image: postgres:12.2
          env:
            - name: POSTGRES_DB
              valueFrom:
                secretKeyRef:
                  name: keycloak-db-secret
                  key: POSTGRES_DB
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: keycloak-db-secret
                  key: POSTGRES_USER
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: keycloak-db-secret
                  key: POSTGRES_PASSWORD
          livenessProbe:
            tcpSocket:
              port: 5432
          ports:
            - containerPort: 5432
          volumeMounts:
            - name: keycloak-storage
              mountPath: /var/lib/postgresql/data/
      volumes:
        - name: keycloak-storage
          persistentVolumeClaim:
            claimName: keycloak-db-volume-claim
