apiVersion: v1
data:
  PARAMS_DB_NAME: TRAVIS_PARAMS_DB_NAME
  PARAMS_DB_PASSWORD: TRAVIS_PARAMS_DB_PASSWORD
  PARAMS_DB_USERNAME: TRAVIS_PARAMS_DB_USERNAME
kind: Secret
metadata:
  creationTimestamp: null
  name: horario-web-secrets