apiVersion: v1
kind: Service
metadata:
  labels:
    app: horario-web
  name: horario-web
spec:
  ports:
    - port: 8080
      protocol: TCP
      targetPort: 8080
  selector:
    app: horario-web
  type: ClusterIP
