apiVersion: v1
kind: PersistentVolume
metadata:
  name: horario-db-volume
  labels:
    app: horario-db
    volume: horario-db-volume
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: hostpath
  capacity:
    storage: 1Gi
  hostPath:
    path: /tmp/horario-db
