apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: keycloak-db-volume-claim
  labels:
    app: keycloak-db
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  selector:
    matchLabels:
      volume: keycloak-db-volume
