apiVersion: v1
kind: PersistentVolume
metadata:
  name: keycloak-db-volume
  labels:
    app: keycloak-db
    volume: keycloak-db-volume
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: hostpath
  capacity:
    storage: 1Gi
  hostPath:
    path: /tmp/keycloak-db
