apiVersion: v1
data:
  DB_ADDR: a2V5Y2xvYWstZGI=
  DB_DATABASE: a2V5Y2xvYWs=
  DB_PASSWORD: YWRtaW4=
  DB_USER: YWRtaW4=
  KEYCLOAK_PASSWORD: YWRtaW4=
  KEYCLOAK_USER: YWRtaW4=
kind: Secret
metadata:
  name: keycloak-secret
