apiVersion: v1
kind: PersistentVolume
metadata:
  name: backend-db-volume
  labels:
    app: backend-db
    volume: backend-db-volume
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: hostpath
  capacity:
    storage: 1Gi
  hostPath:
    path: /tmp/backend-db
