apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: horario-web
  name: horario-web
spec:
  replicas: 1
  selector:
    matchLabels:
      app: horario-web
  strategy: {}
  template:
    metadata:
      labels:
        app: horario-web
    spec:
      containers:
        - image: marcecardozo/poliplanner-horario-web:dev
          name: horario-web
          env:
            - name: PARAMS_DB_URL
              valueFrom:
                configMapKeyRef:
                  name: horario-web-config
                  key: PARAMS_DB_URL
            - name: PARAMS_KEYCLOAK_URL
              valueFrom:
                configMapKeyRef:
                  name: horario-web-config
                  key: PARAMS_KEYCLOAK_URL

            - name: PARAMS_DB_NAME
              valueFrom:
                secretKeyRef:
                  name: horario-web-secret
                  key: PARAMS_DB_NAME
            - name: PARAMS_DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: horario-web-secret
                  key: PARAMS_DB_PASSWORD
            - name: PARAMS_DB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: horario-web-secret
                  key: PARAMS_DB_USERNAME
