apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: horario-db-volume-claim
  labels:
    app: horario-db
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: hostpath
  selector:
    matchLabels:
      volume: horario-db-volume
